### ISSUE TITLE
statement getter crashing

### ISSUE THREAD

**Issue by kaandedeoglu** [qutheory/fluent-sqlite#4]
``` swift
    private var statementPointer: UnsafeMutablePointer<OpaquePointer?>! = nil
    private var statement: OpaquePointer {
        return statementPointer.pointee!
    }
```

The statement getter is crashing with `fatal error: unexpectedly found nil while unwrapping an Optional value`. This usually occurs when higher frequency of requests are sent from the client.

**Comment by tanner0101** [comment]
#3 should fix this.

**Comment by kaandedeoglu** [comment]
@tannernelson I've started having this crash after applying #3 myself.

**Comment by tanner0101** [comment]
@kaandedeoglu could you try tag `0.3.2` and let me know if the problem still happens?

If it does, could you send me a dump of your DB so that I can recreate?

**Comment by kaandedeoglu** [comment]
@tannernelson The problem still persists. I'll try to my best to make sure you can reproduce the issue. 

Here's a dropbox link to my current database: https://dl.dropboxusercontent.com/u/22953018/main.sqlite

I'm using Kitura. And can most definitely reproduce the issue by calling an endpoint twice in succession.
Such as

``` swift
        Alamofire.request(Router.AllOffers).responseDebugPrint()
        Alamofire.request(Router.AllOffers).responseObject { (allOffersResponse: AllOffersResponse?, error) in
            if let allOffers = allOffersResponse?.offers {
                self.offers = allOffers
            }
            self.refreshControl.endRefreshing()
            self.tableView.reloadData()
        }
```

(responseDebugPrint and responseObject are my own Alamofire extensions)

The crash is generated in method below. Specifically in `let sendingUser = self.tokenAuthenticator.userForToken(token: token)` line 

``` swift
    private func allOffersHandler() -> RouterHandler {
        return { request, response, next in

            guard   let token = request.headers[AppConstants.OAuthTokenKeyName],
                    let sendingUser = self.tokenAuthenticator.userForToken(token: token) else {
                    response.status(HTTPStatusCode.unauthorized)
                    next()
                    return
            }

            let offers = self.offerCollection.getAll()
            let json = JSON(["data" : offers.map { $0.serializeJSON() }])

            response.status(.OK).send(json: json)
            next()
        }
    }
```

`userForToken` looks like this

``` swift
func userForToken(token: String) -> User? {
        if let user = try? User.query.filter("token", token).first() {
            return user
        }
        return nil
    }
```

Here's the User class (code is very ugly for this, just trying to make things work without crashing)

``` swift
class User: Model {
    var userID: String {
        return String((id?.string)!)
    }
    var id: Value?
    var userName: String?
    var facebookID: String?
    var token: String? = ""

    var email: String? = ""
    var password: String? = ""

    var heartCount: Int {
        return 0
    }

    var icon: String? = ""
    var colorHex: String? = "#ffffff"

    required init(serialized: [String : Value]) {
        id = serialized["id"]
        token = serialized["token"]?.string
        userName = serialized["userName"]?.string
        facebookID = serialized["facebookID"]?.string        
        email = serialized["email"]?.string
        password = serialized["password"]?.string
        icon = serialized["icon"]?.string
        colorHex = serialized["colorHex"]?.string
    }

    init(userName: String, email: String?) {
        self.userName = userName
        self.email = email ?? ""
        self.token = NSUUID().uuidString
    }

    class var table: String {
        return "users"
    }

    func serialize(userID: String?) -> JSONDictionary {
        var result = JSONDictionary()

        result["id"] = self.userID
        result["userName"] = userName
        result["hearts"] = heartCount
        result["colorHex"] = colorHex

        if let userID = userID where userID == self.id?.string {
            result["email"] = email
            result["token"] = token
        }

        return result
    }

    func serialize() -> [String : Value?] {
        return [
                   "userName" : userName,
                   "facebookID" : facebookID,
                   "token" : token,
                   "email" : email,
                   "password" : password,
                   "icon" : icon,
                   "colorHex" : colorHex
        ]
    }
}
```

Here's the stack trace for the crash:
<img width="558" alt="screen shot 2016-05-24 at 10 53 54 am" src="https://cloud.githubusercontent.com/assets/1566836/15496471/fea330ea-219d-11e6-96d0-554e2655fdc6.png">

And this is where the crashing access to the getter occurs:
<img width="440" alt="screen shot 2016-05-24 at 10 57 09 am" src="https://cloud.githubusercontent.com/assets/1566836/15496512/4de47d1c-219e-11e6-886d-6f8003871c37.png">

**Comment by tanner0101** [comment]
@kaandedeoglu can you send me what `token` equals and also what the specific error message comes after the stack trace? I've attempted to reproduce the code in #5 using your database, and it doesn't crash on my Mac.

**Comment by kaandedeoglu** [comment]
@tannernelson  token is: 500D4770-9720-44DF-A25E-F29689DA521D. If it doesn't crash, I can just pack both projects and send it to you.

**Comment by tanner0101** [comment]
It's not crashing for me still. If you could send the projects + paste the full error output that would be helpful! 

Thanks for all of the assistance so far.

**Comment by kaandedeoglu** [comment]
@tannernelson Just sent you an email with both backend & client projects

**Comment by tanner0101** [comment]
Which toolchain are you building with in Xcode?

**Comment by kaandedeoglu** [comment]
Swift Development Snapshot 2016-05-03 (a)

**Comment by tanner0101** [comment]
```
Linking .build/debug/HeartsServer
Gertrude:Hearts-Server tanner$ .build/debug/HeartsServer
SQLite Version: 3.8.10.2
SQLite executing: SELECT * FROM users;
QUERY RESULT: [[Optional("1")] ["icon": "", "colorHex": "#ffffff", "email": "", "token": "500D4770-9720-44DF-A25E-F29689DA521D", "password": "", "userName": "Kaan Dedeoglu", "facebookID": "10154118830599133"], [Optional("2")] ["icon": "", "colorHex": "#ffffff", "email": "", "token": "41817617-D04B-4A0A-98A3-7FDB56AC177E", "password": "", "userName": "Magnus Bischofberger", "facebookID": "10154027138210272"]]
SQLite executing: SELECT * FROM users WHERE token = ? LIMIT 1;
SQLite executing: SELECT * FROM offers;
```

```
localhost:8090/offers/all

Accept: */*
Accept-Encoding: gzip, deflate
token_name: 500D4770-9720-44DF-A25E-F29689DA521D
Accept-Language: en-us
```

```
HTTP/1.1 200 OK

Date: Thu, 26 May 2016 15:29:29 GMT
Content-Type: application/json
Content-Length: 12172
```

Seems to be working for me.

**Comment by tanner0101** [comment]
What version of SQLite are you using?

**Comment by kaandedeoglu** [comment]
can you please try launching the client a few times while the server is running - and see if it crashes.

I'm using version 3.8.10.2

**Comment by kaandedeoglu** [comment]
thank you so much for taking the time by the way 😄

**Comment by tanner0101** [comment]
Can't test it because I don't have access on my Facebook account. >_<

Are you running the app in Xcode or the Terminal? If you could send me the full error output including the exact message about what failed that would help me the most I think.

**Comment by kaandedeoglu** [comment]
@tannernelson here's the error output:

```
SQLite executing: SELECT * FROM offers;
Current stack trace:
0   libswiftCore.dylib                  0x00000001006104b1 swift_reportError + 145
1   libswiftCore.dylib                  0x000000010062dacb _swift_stdlib_reportFatalError + 59
2   libswiftCore.dylib                  0x00000001005d9fbf partial apply forwarder for reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()).1302 + 63
3   libswiftCore.dylib                  0x000000010040ba6f generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer <A> (invoke : (Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A + 351
4   libswiftCore.dylib                  0x00000001005a366e partial apply forwarder for Swift.(_fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> ()).(closure #2) + 158
5   libswiftCore.dylib                  0x0000000100565b3b function signature specialization <preserving fragile attribute, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> () + 331
6   FluentSQLite.dylib                  0x000000010022f186 FluentSQLite.SQLite.(statement in _871F71E8D9C1EAD1BE7A28643613256F).getter : Swift.OpaquePointer + 166
7   FluentSQLite.dylib                  0x000000010022fcc9 FluentSQLite.SQLite.execute (Swift.String, prepareClosure : (FluentSQLite.SQLite) throws -> ()) throws -> Swift.Array<FluentSQLite.SQLite.Result.Row> + 953
8   FluentSQLite.dylib                  0x0000000100232fdc FluentSQLite.SQLiteDriver.execute <A where A: Fluent.Model> (Fluent.Query<A>) throws -> Swift.Array<Swift.Dictionary<Swift.String, Fluent.Value>> + 636
9   FluentSQLite.dylib                  0x0000000100234be4 protocol witness for Fluent.Driver.execute <A where A1: Fluent.Model> (Fluent.Query<A1>) throws -> Swift.Array<Swift.Dictionary<Swift.String, Fluent.Value>> in conformance FluentSQLite.SQLiteDriver : Fluent.Driver in FluentSQLite + 68
10  Fluent.dylib                        0x000000010024d654 Fluent.Query.run () throws -> Swift.Array<A> + 388
11  Fluent.dylib                        0x000000010024def8 Fluent.Query.all () throws -> Swift.Array<A> + 40
12  Fluent.dylib                        0x000000010024b609 static (extension in Fluent):Fluent.Model.all () throws -> Swift.Array<A> + 57
13  HeartsServer                        0x0000000100013fc6 HeartsServer.OfferCollectionArray.getAll () -> Swift.Array<HeartsServer.Offer> + 54
14  HeartsServer                        0x00000001000053ee HeartsServer.OfferController.((allOffersHandler in _A4D395FF63F0DEF0C42477F9F6653F64) () -> (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> ()).(closure #1) + 766
15  HeartsServer                        0x00000001000042a0 reabstraction thunk helper from @callee_owned (@owned Kitura.RouterRequest, @owned Kitura.RouterResponse, @owned @callee_owned () -> ()) -> () to @callee_owned (@in (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : @callee_owned (@in ()) -> (@out ()))) -> (@out ()) + 144
16  HeartsServer                        0x0000000100005091 partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Kitura.RouterRequest, @owned Kitura.RouterResponse, @owned @callee_owned () -> ()) -> () to @callee_owned (@in (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : @callee_owned (@in ()) -> (@out ()))) -> (@out ()) + 81
17  Kitura.dylib                        0x0000000100339519 reabstraction thunk helper from @callee_owned (@in (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : @callee_owned (@in ()) -> (@out ()))) -> (@out ()) to @callee_owned (@owned Kitura.RouterRequest, @owned Kitura.RouterResponse, @owned @callee_owned () -> ()) -> () + 121
18  Kitura.dylib                        0x000000010033dd2f Kitura.RouterMiddlewareGenerator.handle (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 127
19  Kitura.dylib                        0x000000010033de33 protocol witness for Kitura.RouterMiddleware.handle (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () in conformance Kitura.RouterMiddlewareGenerator : Kitura.RouterMiddleware in Kitura + 83
20  Kitura.dylib                        0x000000010033e4fe Kitura.RouterMiddlewareWalker.next () -> () + 926
21  Kitura.dylib                        0x000000010033a239 Kitura.RouterElement.(processHelper in _87A850EB8112F17CB7B6B134A8F81A90) (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 185
22  Kitura.dylib                        0x0000000100339ddc Kitura.RouterElement.process (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 2204
23  Kitura.dylib                        0x000000010033b1e7 Kitura.RouterElementWalker.next () -> () + 503
24  Kitura.dylib                        0x000000010033b25f Kitura.RouterElementWalker.(next () -> ()).(closure #1) + 31
25  Kitura.dylib                        0x0000000100339e21 Kitura.RouterElement.process (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 2273
26  Kitura.dylib                        0x000000010033b1e7 Kitura.RouterElementWalker.next () -> () + 503
27  Kitura.dylib                        0x000000010033b25f Kitura.RouterElementWalker.(next () -> ()).(closure #1) + 31
28  Kitura.dylib                        0x0000000100339e21 Kitura.RouterElement.process (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 2273
29  Kitura.dylib                        0x000000010033b1e7 Kitura.RouterElementWalker.next () -> () + 503
30  Kitura.dylib                        0x000000010033b25f Kitura.RouterElementWalker.(next () -> ()).(closure #1) + 31
31  Kitura.dylib                        0x0000000100339e21 Kitura.RouterElement.process (request : Kitura.RouterRequest, response : Kitura.RouterResponse, next : () -> ()) -> () + 2273
32  Kitura.dylib                        0x000000010033b1e7 Kitura.RouterElementWalker.next () -> () + 503
33  Kitura.dylib                        0x000000010033231d Kitura.Router.(process in _48D2702B8CA080B647854755F03BA930) (request : Kitura.RouterRequest, response : Kitura.RouterResponse, callback : () -> ()) -> () + 1677
34  Kitura.dylib                        0x000000010033281e Kitura.Router.handle (request : KituraNet.ServerRequest, response : KituraNet.ServerResponse) -> () + 318
35  Kitura.dylib                        0x0000000100334488 protocol witness for KituraNet.HTTPServerDelegate.handle (request : KituraNet.ServerRequest, response : KituraNet.ServerResponse) -> () in conformance Kitura.Router : KituraNet.HTTPServerDelegate in Kitura + 56
36  KituraNet.dylib                     0x00000001001c503d KituraNet.HTTPServer.(handleClientRequest (socket : Socket.Socket) -> ()).(closure #1).(closure #1) + 189
37  KituraNet.dylib                     0x00000001001c7c30 KituraNet.IncomingMessage.parse ((KituraNet.IncomingMessage.HTTPParserErrorType) -> ()) -> () + 1568
38  KituraNet.dylib                     0x00000001001c4e9a KituraNet.HTTPServer.(handleClientRequest (socket : Socket.Socket) -> ()).(closure #1) + 266
39  KituraSys.dylib                     0x0000000100149007 reabstraction thunk helper from @callee_owned () -> () to @callee_unowned @convention(block) () -> () + 39
40  libdispatch.dylib                   0x0000000100d7f070 _dispatch_call_block_and_release + 12
41  libdispatch.dylib                   0x0000000100d71cc5 _dispatch_client_callout + 8
42  libdispatch.dylib                   0x0000000100d87f8a _dispatch_async_redirect_invoke + 2837
43  libdispatch.dylib                   0x0000000100d71cc5 _dispatch_client_callout + 8
44  libdispatch.dylib                   0x0000000100d76457 _dispatch_root_queue_drain + 2934
45  libdispatch.dylib                   0x0000000100d758a5 _dispatch_worker_thread3 + 106
46  libsystem_pthread.dylib             0x0000000100dd4336 _pthread_wqthread + 1129
47  libsystem_pthread.dylib             0x0000000100dd1f91 start_wqthread + 13
```

**Comment by tanner0101** [comment]
Perhaps #6 will fix this since pointers are optionals in 05-09. 

This appears to just be the stack trace of the error. There is usually an error message as well like "unexpectedly found nil while trying to unwrap foo"

**Comment by kaandedeoglu** [comment]
@tannernelson closing this for now. It seems nobody has the same problems. Since I have very little I can provide at the moment, I will reopen this when/if I have more solid data that can help you dig deeper. Thank you so much for the friendly approach 👍
